apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: moni
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.16-debian
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config-volume
              mountPath: /fluentd/etc
          command: ["/bin/sh", "-c"]
          args:
            - |
              gem install  fluent-plugin-loki fluent-plugin-kafka;
              exec fluentd -c /fluentd/etc/fluent.conf -v
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
