apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: moni
data:
  fluent.conf: |
    <source>
      @type kafka
      brokers kafka-service.kafka.svc.cluster.local:9092
      topics ops.kube-logs-fluentbit.stream.json.001
      format json
    </source>

    <filter **>
      @type record_transformer
      enable_ruby true
      <record>
        pod_name       ${record["kubernetes"]["pod_name"]}
        namespace      ${record["kubernetes"]["namespace_name"]}
        container      ${record["kubernetes"]["container_name"]}
        deployment     ${record["kubernetes"]["labels"]["app"]}
      </record>
    </filter>

    <match **>
      @type loki
      endpoint_url http://loki.moni.svc.cluster.local:3100
      line_format json
      labels {
        "env": "production",
        "cluster": "k8s-cluster",
        "pod": "${pod_name}",
        "namespace": "${namespace}",
        "container": "${container}",
        "deployment": "${deployment}"
      }
      <buffer>
        flush_interval 10s
        flush_at_shutdown true
      </buffer>
    </match>
