services:
  fluentbit:
    image: cr.fluentbit.io/fluent/fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./:/fluent-bit/etc/
  nginx:
    build: .
    ports:
      - "8082:80"
    environment:
    - MY_DOMAIN=localhost
    - MY_PORT=80
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        tag: nginx