services:
  fluentbit:
    image: cr.fluentbit.io/fluent/fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./src/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./src/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
    networks:
      - logging

  nginx:
    build: .
    deploy:
      replicas: 3
    ports:
      - "0:80"
    environment:
    - MY_DOMAIN=localhost
    - MY_PORT=80
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        tag: nginx-${HOSTNAME}  
        fluentd-address: localhost:24224
    networks:
      - logging

networks:
  logging:
    driver: bridge
