services: 
  fluentbit:
  # Using the official Fluent Bit image for log forwarding
    image: cr.fluentbit.io/fluent/fluent-bit 
    ports:
     # Exposing Fluent Bit's TCP input port & UDP input port
      - "24224:24224"
      - "24224:24224/udp" 
    volumes:
    # Mounting the Fluent Bit & parsers configuration file
      - ./src/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./src/fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf 
    networks:
      - logging  # Connecting to the logging network

  nginx:
    build: . 
    deploy:
      replicas: 3 # Running three replicas of the Nginx service
    ports:
      - "0:80" # Exposing Nginx on random host ports (Docker assigns automatically)
    environment:
    # Setting environment variable for domain & port
    - MY_DOMAIN=localhost 
    - MY_PORT=80
    depends_on:
      - fluentbit # Ensuring Fluent Bit starts before Nginx
    logging:
      driver: fluentd # Using Fluentd for logging
      options:
        tag: nginx-${HOSTNAME}  # Setting dynamic log tags using the hostname
        fluentd-address: localhost:24224 # Sending logs to Fluent Bit on port 24224
    networks:
      - logging # Connecting to the logging network

networks:
  logging:
    driver: bridge # Using the bridge network driver for communication between services
