apiVersion: apps/v1
kind: Deployment
metadata:
  name: deeplog-app
  namespace: deeplog
  labels:
    app: deeplog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deeplog-app
  template:
    metadata:
      labels:
        app: deeplog-app
    spec:
      containers:
      - name: deeplog-app
        image: osamaahmed17/deeplog-01
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis.drain3.svc.cluster.local"
        - name: k_top
          value: "6"
        command: ["python"]                # override CMD
        args: ["deeplog_train.py"]    # script to run

---
apiVersion: v1
kind: Service
metadata:
  name: deeplog-app
spec:
  selector:
    app: deeplog-app
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP