apiVersion: apps/v1
kind: Deployment
metadata:
  name: npdb
  namespace: npps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: npdb
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args:
        - |
          until nc -z postgresql 5432; do
            echo "Waiting for PostgreSQL to be ready...";
            sleep 2;
          done;
          echo "PostgreSQL is ready!";
      containers:
      - name: npdb
        image: ghcr.io/plexoos/npdb:latest
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: postgresql
        - name: POSTGRES_DB
          value: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: npdb
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: npdb
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: npdb
        - name: DEBUG
          value: "True"
        - name: ALLOWED_HOSTS
          value: "*"
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Running makemigrations..." &&
          python manage.py makemigrations cdb_rest &&
          echo "Running migrations..." &&
          python manage.py migrate &&
          echo "Starting Django server..." &&
          python manage.py runserver 0.0.0.0:8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            memory: 512Mi