apiVersion: v1
kind: Service
metadata:
  name: postgres-app-service
  namespace: grafana-loki
spec:
  selector:
    app: postgres-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
