# ServiceAccount for Fluent Bit to allow using the Kubernetes metadata filter
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: kafka

---
# ClusterRole granting permission to read pods and namespaces (for metadata enrichment)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources:
    - namespaces
    - pods
  verbs:
    - get
    - list
    - watch

---
# Bind the ServiceAccount to the ClusterRole (enables Fluent Bit to use the K8s API)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: default

---
# ConfigMap for Fluent Bit INPUT and FILTER configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-input
  namespace: kafka
data:
  # Tail all container log files for every pod on the node
  fluent-bit-input.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            cri                      # Use 'cri' for CRI runtime logs (KinD); use 'docker' if Docker
        DB                /var/log/flb_kube.db      # Persist read offsets
        Skip_Long_Lines   On
        Refresh_Interval  5
        Mem_Buf_Limit     5MB

    # Kubernetes filter to add pod metadata (namespace, labels, etc.):contentReference[oaicite:5]{index=5}:contentReference[oaicite:6]{index=6}
    [FILTER]
        Name              kubernetes
        Match             kube.*
        Kube_URL          https://kubernetes.default.svc:443
        Kube_CA_File      /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File   /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix   kube.var.log.containers.
        Merge_Log         On
        Keep_Log          Off

---
# ConfigMap for Fluent Bit OUTPUT configuration (Kafka plugin)
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-output
  namespace: kafka
data:
  fluent-bit-output.conf: |
    [OUTPUT]
        Name           kafka
        Match          *
        Brokers        kafka-service:9092
        Topics         ops.kube-logs-fluentbit.stream.json.001
        Timestamp_Key  @timestamp
        Retry_Limit    false
        # hides errors "Receive failed: Disconnected" when kafka kills idle connections
        rdkafka.log.connection.close false
        # producer buffer is not included in http://fluentbit.io/documentation/0.12/configuration/memory_usage.html#estimat>        rdkafka.queue.buffering.max.kbytes 10240
        # for logs you'll probably want this ot be 0 or 1, not more
        rdkafka.request.required.acks 1
                          # Kafka topic(s) for log data
        # (Optional) Set message format or additional properties if needed

---
# ConfigMap defining LOG parsers (docker and cri formats):contentReference[oaicite:7]{index=7}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-parsers
  namespace: kafka
data:
  parsers.conf: |
    [PARSER]
        Name        cri
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

---
# Fluent Bit DaemonSet to run on every node, mounting ConfigMaps and host logs
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:latest
        # Point Fluent Bit to our config files
        args:
          - /fluent-bit/bin/fluent-bit
          - -c
          - /fluent-bit/etc/fluent-bit.conf
        # Mount ConfigMaps for input, output, and parsers
        volumeMounts:
          - name: input-config
            mountPath: /fluent-bit/input
          - name: output-config
            mountPath: /fluent-bit/output
          - name: parsers-config
            mountPath: /fluent-bit/parsers
          # Mount host log directories
          - name: varlog
            mountPath: /var/log
          - name: kubelet
            mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      volumes:
        - name: input-config
          configMap:
            name: fluent-bit-input
            items:
              - key: fluent-bit-input.conf
                path: input-kubernetes.conf
        - name: output-config
          configMap:
            name: fluent-bit-output
            items:
              - key: fluent-bit-output.conf
                path: output-kafka.conf
        - name: parsers-config
          configMap:
            name: fluent-bit-parsers
            items:
              - key: parsers.conf
                path: parsers.conf
        - name: varlog
          hostPath:
            path: /var/log
        - name: kubelet
          hostPath:
            path: /var/run/secrets/kubernetes.io/serviceaccount
