# loki anbd Grafana configuration file 
test_pod:
  enabled: true
  image: bats/bats:1.8.2
  pullPolicy: IfNotPresent
loki:
  enabled: true
  isDefault: true
  url: http://{{ include "loki.serviceName" . }}:{{ .Values.loki.service.port }}

  extraVolumeMounts:
    - name: loki-storage
      mountPath: /var/loki

  extraVolumes:
    - name: loki-storage
      persistentVolumeClaim:
        claimName: loki-pvc

  config:
    storage_config:
      aws:
        s3: http://minio-service.minio.svc.cluster.local:9000/logs
        access_key_id: minioadmin
        secret_access_key: minioadmin
        s3forcepathstyle: true
        insecure: true
      boltdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/cache
        shared_store: s3

    schema_config:
      configs:
        - from: 2024-01-01
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h

    compactor:
      working_directory: /var/loki/compactor
      shared_store: s3

  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45

  livenessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45

  datasource:
    jsonData: "{}"
    uid: ""


promtail:
  enabled: false


grafana:
  enabled: true
  sidecar:
    datasources:
      label: ""
      labelValue: ""
      enabled: true
      maxLines: 1000
  image:
    tag: 10.3.3
  service:
    type: NodePort
    main: |-
      output {
        loki {
          url => "http://loki:3100/loki/api/v1/push"
          #username => "test"
          #password => "test"
        }
        # stdout { codec => rubydebug }
      }

proxy:
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""
